---
- hosts: 10.254.0.55
  remote_user: harlock
  sudo: yes

  tasks:
  - name: Install build essentials
    apt: name=build-essential state=present
  - name: Install Git
    apt: name=git-core state=present
  - name: Install SVN
    apt: name=subversion state=present
  - name: Install cmake
    apt: name=cmake state=present
  - name: Install cmake Data
    apt: name=cmake-data state=present

    # Domoio Libs
  - name: Postgres
    apt: name=postgresql-9.1 state=present
    # Domoio development libs
  - name: Postgres dev
    apt: name=libpq-dev state=present
  - name: Boost
    apt: name=libboost-all-dev state=present
  - name: Libssl
    apt: name=libssl-dev state=present



  - name: Install v8
    file: path=/home/harlock/src state=directory owner=harlock group=harlock
  - name: Clone repo
    subversion: repo=http://v8.googlecode.com/svn/branches/3.25/ dest=/home/harlock/src/v8-3.25